### ISSUE TITLE
Docs (readthedocs) ?

### ISSUE THREAD

**Issue by stuaxo** [rasterio/affine#60]
Planar had some nice HTML docs
https://pythonhosted.org/planar/transforms.html

I'm not sure how the above docs are generated, if they are something standard it may be worth moving docs to readthedocs.

It would be good to get these for Affine, it may be a matter of contacting Casey, I know a number of years ago he was pretty keen for someone to pick up Planar, so don't imagine this would be a problem.

**Comment by Rotzbua** [comment]
Created a PR to build a single site documentation.

Result looks like this:
https://rotzbua.github.io/affine/

**Comment by stuaxo** [comment]
From a quick scan that looks nice :)

Where would these be hosted, on github pages ?

**Comment by Rotzbua** [comment]
> Where would these be hosted, on github pages ?

Right. Hosted on github pages. The actions build the html and uploads the documentation html artifact to pages.

> From a quick scan that looks nice :)

Thanks :)
I know that it is just an 80% solution e.g. versioned documentation is missing but I think it is the simplest solution without additional external services at the moment.

**Comment by stuaxo** [comment]
Having messed with docs gen, I know it's a pain, and I never got as far as versioned docs - if you crack it I should probably see how + maybe do the same for the (non RTD) docs for the shoebot project.

**Comment by sgillies** [comment]
@Rotzbua my first impression is very positive. I would also prefer sphinx over, say, mkdocs, because of familiarity with sphinx. I have two questions:

* Did you approach this differently from what is described at https://bylr.info/articles/2022/05/10/api-doc-with-sphinx-autoapi/? Don't dive into that unless you want to, I'm only asking if you've already read that post.
* My thought would be to host at Read the Docs. Are you okay with that?

**Comment by sgillies** [comment]
Here we go: https://affine.readthedocs.io/en/latest/.

Thank you @Rotzbua !

**Comment by stuaxo** [comment]
Fantastic work, thanks all!
