### ISSUE TITLE
Affine class no longer compatible with delayed operations in Dask 2022.8.1

### ISSUE THREAD

**Issue by fbunt** [rasterio/affine#79]
A recent change (dask/dask#9361) in how dask handles arguments that are instances or subclasses of `namedtuple` prevents `Affine` objects from being passed to delayed operations such as `dask.array.map_blocks`. Dask now unpacks the namedtuples and then tries to repack them before providing them to the delayed function at compute time. This breaks for Affine objects since they unpack to the full 9 coefficients but `Affine.__new__` only takes the first 6 coefficients. The result is

```python
TypeError: __new__() takes 7 positional arguments but 10 were given
```

when dask graphs are computed.

My current solution is to pass the coefficients in place of the instance but it would be great to simply pass Affine objects again.

**Comment by fbunt** [comment]
Quick example:

```python
import dask.array as da
import numpy as np
from affine import Affine

def dummy(x, aff):
    print(aff)
    return x

x = da.from_array(np.ones((4, 4)), chunks=(2, 2))
a = Affine(1.0, 0.0, 0.0, 0.0, -1.0, 4.0)
da.map_blocks(dummy, x, aff=a).compute()
```

**Comment by sgillies** [comment]
@fbunt thanks for reporting this!

**Comment by groutr** [comment]
If namedtuple is only an implementation detail of affine, perhaps using something like array.array (https://docs.python.org/3/library/array.html) would be a good alternative?

**Comment by sgillies** [comment]
@groutr well, I was thinking to use attrs or a data class instead.

**Comment by groutr** [comment]
My understanding was that affine sought to be free of dependencies outside of Python's standard library. Data classes are a good idea. Affine doesn't seem to specify any minimum version of Python, but using data classes would mean Python >=3.7 (which probably isn't a big deal). Slotted data classes weren't introduced until Python 3.10, so each data class instance would have an instance dictionary. But they can be frozen and have named attributes so mimic the behavior of a namedtuple.

The suggestion to use `array.array` was because it could be used to enforce the type of all the values, casting as necessary. It also preserves some of the behavior of a named tuple such as slicing and unpacking. Additionally, `array.array` would play nicely with numpy's support of the buffer protocol (ie, creating an array view of a transform without having to make a copy, but ). Arrays have their drawbacks, mainly mutability. Care would have to be taken in regards to mutability as changing the numpy array changes the array).

Ultimately, you know affine's design goals and future far better than I do.

**Comment by artttt** [comment]
leaving a comment here to bump this issue as I just found the same bug.

**Comment by sgillies** [comment]
@artttt that's a great suggestion! I'm trying it out in #92.
